version = 0.1

[default.deploy.parameters]
stack_name = "telemonitoring-api-jan"
resolve_s3 = true
s3_prefix = "telemonitoring-api-jan"
region = "eu-west-1"
profile = "telemonitoring-test"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = """
Domain="${NEXT_PUBLIC_API_URL}"
Environment="${NEXT_PUBLIC_API_URL}"
Frontend="${NEXT_PUBLIC_API_URL}"
OpsSlack="${NEXT_PUBLIC_API_URL}"
UserPoolId="${NEXT_PUBLIC_API_URL}"
UserPoolClient="${NEXT_PUBLIC_API_URL}"
EpicClientId="${NEXT_PUBLIC_API_URL}"
EpicRedirectUri="${NEXT_PUBLIC_API_URL}"
"""